name: test:data
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - run: npm install && npm run test
